// Author: Igor Zaworski

enum PrintOptions {
    RESET = 0,
    BOLD = 1,
    UNDERLINE = 4,
    INVERSE = 7,
    BOLD_OFF = 21,
    UNDERLINE_OFF = 24,
    INVERSE_OFF = 27,

    BLACK_F = 30,
    RED_F = 31,
    GREEN_F = 32,
    YELLOW_F = 33,
    BLUE_F = 34,
    MAGENTA_F = 35,
    CYAN_F = 36,
    WHITE_F = 37,

    BLACK_B = 40,
    RED_B = 41,
    GREEN_B = 42,
    YELLOW_B = 43,
    BLUE_B = 44,
    MAGENTA_B = 45,
    CYAN_B = 46,
    WHITE_B = 47,

    GREY_F = 90,
    BRIGHT_RED_F = 91,
    BRIGHT_GREEN_F = 92,
    BRIGHT_YELLOW_F = 93,
    BRIGHT_BLUE_F = 94,
    BRIGHT_MAGENTA_F = 95,
    BRIGHT_CYAN_F = 96,
    BRIGHT_WHITE_F = 97,

    GREY_B = 100,
    BRIGHT_RED_B = 101,
    BRIGHT_GREEN_B = 102,
    BRIGHT_YELLOW_B = 103,
    BRIGHT_BLUE_B = 104,
    BRIGHT_MAGENTA_B = 105,
    BRIGHT_CYAN_B = 106,
    BRIGHT_WHITE_B = 107,
};
